# https://github.com/xcv58/meteor-collectionapi

language: node_js
sudo: required

node_js:
  - "0.12"

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g spacejam"


script:
  - "spacejam test-packages ./"
