# https://github.com/xcv58/meteor-collectionapi

language: node_js
sudo: required

addons:
    code_climate:
        repo_token: 0f79bc84065e7f69162adfc600f872b2ed6573967a498b53631c584425dfa3b1

node_js:
  - "0.12"

before_install:
  - "curl https://install.meteor.com | /bin/sh"


script:
  - "npm test"
  - "npm run test-meteor"
  - "npm install -g codeclimate-test-reporter && npm run test-coverage && codeclimate-test-reporter < coverage/lcov.info"
