# https://github.com/xcv58/meteor-collectionapi

sudo: required
language: node_js

node_js:
  - "5"

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g spacejam"


script:
  - "spacejam test-packages ./"
